### ISSUE TITLE
Score is displayed on the screen, not just in the console.

### ISSUE THREAD

**Issue by Phyoog** [mocsarcade/starjunk#20]

**Comment by ehgoodenough** [comment]
So what I'm going to suggest when putting text on the screen is to NOT use Pixi.

Pixi is a fantastic library for rendering via WebGL, but it sucks when trying to render text and font. If you can get it to work, then go ahead and use it. Look into inheriting from `Pixi.Text`. But in my experience, it fails to render anything even somewhat readable.

But you know what is really really good at putting text on a screen? HTML of course! A lot of games will go to lengths to import an HTML engine just to handle their UI. But you're already building a game in the biggest HTML engines yet, the browser!

So what I'm suggesting is you make a `<div>` in the HTML, style it using CSS, and then use JS to put the current score in it.

[![selfie-0](http://i.imgur.com/EwxiDhI.gif)](https://github.com/thieman/github-selfies/)
