### ISSUE TITLE
Sprites should remain crisp, even when near the edges of the screen.

### ISSUE THREAD

**Issue by ehgoodenough** [mocsarcade/starjunk#22]
When the `Junkership` gets near the edge of the screen, the sprite blurs for some reason. This bug can be seen as early as `v0.1.0`. Other sprites, like the `Trashbot` does not seem to be affected by this.

<img width="90" alt="screen shot 2016-01-30 at 2 23 05 pm" src="https://cloud.githubusercontent.com/assets/1202938/12698859/20cc26ae-c75d-11e5-9219-88ca951e320f.png"> vs <img width="119" alt="screen shot 2016-01-30 at 2 22 49 pm" src="https://cloud.githubusercontent.com/assets/1202938/12698860/219d30be-c75d-11e5-9790-2765506201c3.png">

See it in action at http://mocsarcade.github.io/starjunk/v0.1.1

**Comment by Phyoog** [comment]
A bit more info. When colliding with the right or bottom, no blurring occurs. Colliding with the left causes blurring. Colliding with the top edge both blurs and _smooshes_ the ship from 10 pixels tall to 9 pixels tall.

Not sure what all that means, but it may point us in the right direction.

**Comment by ehgoodenough** [comment]
From what it looks like, this is because the `x` and `y` are going negative, causing the sub-blitting. Your edge checking might not be tight enough? You can check at `game.children[0].position.x` to see the position is negative when you push against the top or left sides of the screen.

**Comment by ehgoodenough** [comment]
https://github.com/mocsarcade/starjunk/blob/25c4fa7376b18721d7d47ceaecf33e0b90e282cc/source/Junkership.js#L15

So instead of checking their current position is in bounds, we should check where they _will be_ is within bounds.

``` js
if(Keyb.isDown("<up>")) {
    if(this.position.y - this.speed * delta > 0) {
        this.position.y -= this.speed * delta
    }
}
```

Also it helps to add some logic in case they _were_ going to go out of bounds, we push them to the very edge of the screen.

``` js
if(Keyb.isDown("<up>")) {
    if(this.position.y - this.speed * delta < 0) {
        this.position.y -= this.speed * delta
    } else {
        this.position.y = 0
    }
}
```
