### ISSUE TITLE
v0.1.0 should have a release.

### ISSUE THREAD

**Issue by ehgoodenough** [mocsarcade/starjunk#28]
Run `node build bundle --production`; this will minify all the code, and bundle it into not just `./builds/web` like we usually build, but also `./builds/web1` (which is a singe HTML file encompassing the entire game) and `./builds/win`/`./builds/mac`/builds/linux` (which are executables for those systems).

Upload all of these to the [Github Releases](https://github.com/mocsarcade/starjunk/releases) with the tag `v0.1.0`, including a screenshot and a playable link.

**Comment by ehgoodenough** [comment]
...It should be noted that we've _completely_ messed up our versioning already; all the builds we've made up until now should have been `v0.0.x`, and only now that we've finished all the issues and features we said we'd have done in `v0.1.0` should we name it `v0.1.0`. As we begin working towards `v0.2.0`, we would name all our patches up until then `v0.1.x`.

Maybe for now we should just embrace our current versioning system, and name our new release (and it's playable build) just `v0.1`, without any after the second number. :)

**Comment by Phyoog** [comment]
Hmm... attempting to build with the `node build bundle --production` (or 'node build --production') is spitting out the following error and then just building the same thing it always does.

```
[21:58:15] Building Starjunk
C:\Users\SkylarRowan\Documents\workspace\starjunk\build.js:81
                if(/\.js$/.test(warning.module.resource)) {
                                              ^

TypeError: Cannot read property 'resource' of undefined
    at C:\Users\SkylarRowan\Documents\workspace\starjunk\build.js:81:47
    at Array.forEach (native)
    at C:\Users\SkylarRowan\Documents\workspace\starjunk\build.js:80:42
    at Compiler.<anonymous> (C:\Users\SkylarRowan\Documents\workspace\starjunk\n
ode_modules\webpack\lib\Compiler.js:194:14)
    at Compiler.emitRecords (C:\Users\SkylarRowan\Documents\workspace\starjunk\n
ode_modules\webpack\lib\Compiler.js:282:37)
    at Compiler.<anonymous> (C:\Users\SkylarRowan\Documents\workspace\starjunk\n
ode_modules\webpack\lib\Compiler.js:187:11)
    at C:\Users\SkylarRowan\Documents\workspace\starjunk\node_modules\webpack\li
b\Compiler.js:275:11
    at Compiler.applyPluginsAsync (C:\Users\SkylarRowan\Documents\workspace\star
junk\node_modules\tapable\lib\Tapable.js:60:69)
    at Compiler.afterEmit (C:\Users\SkylarRowan\Documents\workspace\starjunk\nod
e_modules\webpack\lib\Compiler.js:272:8)
    at Compiler.<anonymous> (C:\Users\SkylarRowan\Documents\workspace\starjunk\n
ode_modules\webpack\lib\Compiler.js:267:14)
```

Double-checked to make sure everything's up-to-date, including another run of npm install, but no joy. Any idea if this is an PEBCAK or if something's actually wonky?

**Comment by ehgoodenough** [comment]
Noted! I'm looking into it; probably one of our dependencies is broken. Till then, just build it without the `--production` flag.

**Comment by Phyoog** [comment]
Shall we consider this closed by the MVP release, or do we want to republish with the fixed build script?

**Comment by ehgoodenough** [comment]
Well, let's add a "binary" of the MVP as it is now, which you can do be `node build`ing the project, then uploading the `web1` to the release. It also helps to have a playable link on these releases.

**Comment by ehgoodenough** [comment]
Other than that, we can close this. :)

**Comment by Phyoog** [comment]
Released at https://github.com/mocsarcade/starjunk/releases/tag/v0.1
