### ISSUE TITLE
Weapons - Batch 2

### ISSUE THREAD

**Issue by Phyoog** [mocsarcade/starjunk#61]
- Shield - Force-field, you still have your pea-shooter 
- Super Laser - one second charge up before a single beam is released **DONE**
- Piercing Laser - laser that can punch through all enemies **DONE**
- Sinusoidal Shot - Sine wave bullets, variable amplitude and frequency **DONE**
- Double Sinusoidal Shot - two waves of the Sinusoidal Shot **DONE**
- Paint Gun - Long cool-down, vomits projectiles **DONE**
- Auto Aim - Hold to lock-on, 1 second acquisition, release to fire **DEPRIORITIZED**
- Mines - lay down up to five mines that move right to left as the screen “scrolls” **DONE**
- Super Mines - mines with much larger explosions **DONE**
- Sword - Short range, directly ahead attack, exact size of the ship directly ahead **DONE**

**Comment by ehgoodenough** [comment]
I'm willing for Auto Aim to not be implemented; far too difficult. The others, though, should be simple enough given the current projectile system.
