### ISSUE TITLE
Junkerships of the same type can spawn at the same time

### ISSUE THREAD

**Issue by dhowerton** [mocsarcade/starjunk#73]
Only yellow junkerships spawn if the red ship has died and the yellow ship is still alive.  

![screenshot from 2016-02-28 22 26 23](https://cloud.githubusercontent.com/assets/11837027/13385133/4432982e-de6b-11e5-8b81-518f2a565871.png)

**Comment by Phyoog** [comment]
This is caused by the spawn mechanic checking for how many ships are in play rather than for which specific ships are in play.

**Comment by codaventure** [comment]
Should we map specific ships to specific control schemes? I feel we should, because typically you want to spawn back as the same ship you were last playing with. If ship texture is dependent on the number of ships, it would become sort of sporadic based on who died last.

**Comment by Phyoog** [comment]
With the current plan, that won't come up in actual play since you can't respawn until after gameover.

Which, come to think of it, will probably end this bug too. Let's revisit this once we have a gameover screen in milestone 3. Sound good?
