### ISSUE TITLE
Gameplay with title screen up.

### ISSUE THREAD

**Issue by dhowerton** [mocsarcade/starjunk#99]
![untitled](https://cloud.githubusercontent.com/assets/11837027/14770667/443d19b0-0a45-11e6-98bd-8c3d4fd48535.png)

If you mash the shoot button on death you will respawn before the title screen appears.  Every death after that will instantly respawn you and have the title screen appear afterwards until you refresh.

**Comment by codaventure** [comment]
My PR actually caused this bug while fixing something else. Anyways, I have the fix and will put up the PR to this shortly.

**Comment by Phyoog** [comment]
Closed by PR #100
